/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    BorderGlow: typeof import('./src/components/BorderGlow.vue')['default']
    Button: typeof import('primevue/button')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DotGrid: typeof import('./src/components/DotGrid.vue')['default']
    DToolbar: typeof import('./src/components/DToolbar.vue')['default']
    Galaxy: typeof import('./src/components/Galaxy.vue')['default']
    GlassSurface: typeof import('./src/components/GlassSurface.vue')['default']
    Headline: typeof import('./src/components/Headline.vue')['default']
    Inplace: typeof import('primevue/inplace')['default']
    Magnet: typeof import('./src/components/Magnet.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    RotatingText: typeof import('./src/components/RotatingText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface GlobalDirectives {
    FocusTrap: typeof import('primevue/focustrap')['default']
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
